version: '3.8'

services:
  web:
    build: .
    command: gunicorn lotteryapi.wsgi:application --bind 0.0.0.0:8010
    volumes:
      - .:/app
    ports:
      - "8010:8010"
    env_file:
      - .env
    restart: always        # ensures web container always restarts
