# Generated by Django 5.2.6 on 2025-09-21 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lottery_name', models.CharField(max_length=200)),
                ('draw_number', models.CharField(max_length=50)),
                ('draw_date', models.DateField()),
                ('draw_time', models.CharField(blank=True, max_length=50, null=True)),
                ('draw_location', models.TextField(blank=True, null=True)),
                ('official_website', models.CharField(blank=True, max_length=200, null=True)),
                ('official_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('government_website', models.CharField(blank=True, max_length=200, null=True)),
                ('important_notice', models.TextField(blank=True, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('document_generated', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('director', models.CharField(blank=True, max_length=20, null=True)),
                ('office', models.CharField(blank=True, max_length=20, null=True)),
                ('lottery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_numbers', to='lottery.lottery')),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_rank', models.CharField(max_length=50)),
                ('prize_amount', models.CharField(max_length=100)),
                ('winning_ticket_endings', models.JSONField(blank=True, null=True)),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='lottery.lottery')),
            ],
        ),
        migrations.CreateModel(
            name='ConsolationPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('winning_tickets', models.JSONField(blank=True, null=True)),
                ('prize', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consolation_prize', to='lottery.prize')),
            ],
        ),
        migrations.CreateModel(
            name='WinningTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winning_tickets', to='lottery.prize')),
            ],
        ),
    ]
